// Mocks generated by Mockito 5.4.6 from annotations
// in kincare/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:kincare/core/api/graphql_service.dart' as _i26;
import 'package:kincare/core/errors/result.dart' as _i4;
import 'package:kincare/core/network/network_info.dart' as _i24;
import 'package:kincare/core/storage/hive_storage.dart' as _i25;
import 'package:kincare/data/datasource/local/auth_local_datasource.dart'
    as _i23;
import 'package:kincare/data/datasource/remote/auth_remote_datasource.dart'
    as _i22;
import 'package:kincare/data/datasource/remote/children_remote_datasource.dart'
    as _i14;
import 'package:kincare/data/datasource/remote/dashboard_remote_datasource.dart'
    as _i16;
import 'package:kincare/data/datasource/remote/medication_remote_datasource.dart'
    as _i18;
import 'package:kincare/data/datasource/remote/profile_remote_datasource.dart'
    as _i20;
import 'package:kincare/data/models/child_model.dart' as _i15;
import 'package:kincare/data/models/dashboard_model.dart' as _i17;
import 'package:kincare/data/models/medication_model.dart' as _i19;
import 'package:kincare/data/models/user_model.dart' as _i21;
import 'package:kincare/domain/entities/child_entity.dart' as _i5;
import 'package:kincare/domain/entities/dashboard_entity.dart' as _i10;
import 'package:kincare/domain/entities/medication_entity.dart' as _i8;
import 'package:kincare/domain/entities/user_entity.dart' as _i12;
import 'package:kincare/domain/repositories/auth_repository.dart' as _i13;
import 'package:kincare/domain/repositories/children_repository.dart' as _i2;
import 'package:kincare/domain/repositories/dashboard_repository.dart' as _i9;
import 'package:kincare/domain/repositories/medication_repository.dart' as _i7;
import 'package:kincare/domain/repositories/profile_repository.dart' as _i11;
import 'package:kincare/domain/usecases/create_medication_usecase.dart' as _i30;
import 'package:kincare/domain/usecases/delete_medication_usecase.dart' as _i32;
import 'package:kincare/domain/usecases/get_child_details_usecase.dart' as _i28;
import 'package:kincare/domain/usecases/get_children_usecase.dart' as _i27;
import 'package:kincare/domain/usecases/get_dashboard_usecase.dart' as _i33;
import 'package:kincare/domain/usecases/get_medications_usecase.dart' as _i29;
import 'package:kincare/domain/usecases/get_profile_usecase.dart' as _i34;
import 'package:kincare/domain/usecases/login_usecase.dart' as _i35;
import 'package:kincare/domain/usecases/logout_usecase.dart' as _i36;
import 'package:kincare/domain/usecases/update_medication_usecase.dart' as _i31;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ChildrenRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChildrenRepository extends _i1.Mock
    implements _i2.ChildrenRepository {
  MockChildrenRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.ChildEntity>>> getChildren() =>
      (super.noSuchMethod(
            Invocation.method(#getChildren, []),
            returnValue: _i3.Future<_i4.Result<List<_i5.ChildEntity>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.ChildEntity>>>(
                this,
                Invocation.method(#getChildren, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.ChildEntity>>>);

  @override
  _i3.Future<_i4.Result<_i5.ChildEntity>> getChildDetails(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getChildDetails, [id]),
            returnValue: _i3.Future<_i4.Result<_i5.ChildEntity>>.value(
              _i6.dummyValue<_i4.Result<_i5.ChildEntity>>(
                this,
                Invocation.method(#getChildDetails, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.ChildEntity>>);

  @override
  _i3.Future<_i4.Result<_i5.ChildEntity>> addChild(_i5.ChildEntity? child) =>
      (super.noSuchMethod(
            Invocation.method(#addChild, [child]),
            returnValue: _i3.Future<_i4.Result<_i5.ChildEntity>>.value(
              _i6.dummyValue<_i4.Result<_i5.ChildEntity>>(
                this,
                Invocation.method(#addChild, [child]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.ChildEntity>>);

  @override
  _i3.Future<_i4.Result<_i5.ChildEntity>> updateChild(_i5.ChildEntity? child) =>
      (super.noSuchMethod(
            Invocation.method(#updateChild, [child]),
            returnValue: _i3.Future<_i4.Result<_i5.ChildEntity>>.value(
              _i6.dummyValue<_i4.Result<_i5.ChildEntity>>(
                this,
                Invocation.method(#updateChild, [child]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.ChildEntity>>);

  @override
  _i3.Future<_i4.Result<void>> deleteChild(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChild, [id]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteChild, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}

/// A class which mocks [MedicationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicationRepository extends _i1.Mock
    implements _i7.MedicationRepository {
  MockMedicationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i8.MedicationEntity>>> getMedications() =>
      (super.noSuchMethod(
            Invocation.method(#getMedications, []),
            returnValue:
                _i3.Future<_i4.Result<List<_i8.MedicationEntity>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i8.MedicationEntity>>>(
                    this,
                    Invocation.method(#getMedications, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i8.MedicationEntity>>>);

  @override
  _i3.Future<_i4.Result<_i8.MedicationEntity>> createMedication(
    _i8.MedicationEntity? medication,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createMedication, [medication]),
            returnValue: _i3.Future<_i4.Result<_i8.MedicationEntity>>.value(
              _i6.dummyValue<_i4.Result<_i8.MedicationEntity>>(
                this,
                Invocation.method(#createMedication, [medication]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i8.MedicationEntity>>);

  @override
  _i3.Future<_i4.Result<_i8.MedicationEntity>> updateMedication(
    _i8.MedicationEntity? medication,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMedication, [medication]),
            returnValue: _i3.Future<_i4.Result<_i8.MedicationEntity>>.value(
              _i6.dummyValue<_i4.Result<_i8.MedicationEntity>>(
                this,
                Invocation.method(#updateMedication, [medication]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i8.MedicationEntity>>);

  @override
  _i3.Future<_i4.Result<void>> deleteMedication(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMedication, [id]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteMedication, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}

/// A class which mocks [DashboardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardRepository extends _i1.Mock
    implements _i9.DashboardRepository {
  MockDashboardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i10.DashboardEntity>> getDashboard() =>
      (super.noSuchMethod(
            Invocation.method(#getDashboard, []),
            returnValue: _i3.Future<_i4.Result<_i10.DashboardEntity>>.value(
              _i6.dummyValue<_i4.Result<_i10.DashboardEntity>>(
                this,
                Invocation.method(#getDashboard, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i10.DashboardEntity>>);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i11.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i12.UserEntity>> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i3.Future<_i4.Result<_i12.UserEntity>>.value(
              _i6.dummyValue<_i4.Result<_i12.UserEntity>>(
                this,
                Invocation.method(#getProfile, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i12.UserEntity>>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i13.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i12.UserEntity>> login(
    String? email,
    String? password, {
    bool? rememberMe = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #login,
              [email, password],
              {#rememberMe: rememberMe},
            ),
            returnValue: _i3.Future<_i4.Result<_i12.UserEntity>>.value(
              _i6.dummyValue<_i4.Result<_i12.UserEntity>>(
                this,
                Invocation.method(
                  #login,
                  [email, password],
                  {#rememberMe: rememberMe},
                ),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i12.UserEntity>>);

  @override
  _i3.Future<_i4.Result<void>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String?> getLastLoginEmail() =>
      (super.noSuchMethod(
            Invocation.method(#getLastLoginEmail, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}

/// A class which mocks [ChildrenRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockChildrenRemoteDatasource extends _i1.Mock
    implements _i14.ChildrenRemoteDatasource {
  MockChildrenRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i15.ChildModel>>> getChildren() =>
      (super.noSuchMethod(
            Invocation.method(#getChildren, []),
            returnValue: _i3.Future<_i4.Result<List<_i15.ChildModel>>>.value(
              _i6.dummyValue<_i4.Result<List<_i15.ChildModel>>>(
                this,
                Invocation.method(#getChildren, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i15.ChildModel>>>);

  @override
  _i3.Future<_i4.Result<_i15.ChildModel>> getChildDetails(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getChildDetails, [id]),
            returnValue: _i3.Future<_i4.Result<_i15.ChildModel>>.value(
              _i6.dummyValue<_i4.Result<_i15.ChildModel>>(
                this,
                Invocation.method(#getChildDetails, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i15.ChildModel>>);

  @override
  _i3.Future<_i4.Result<_i15.ChildModel>> addChild(_i15.ChildModel? child) =>
      (super.noSuchMethod(
            Invocation.method(#addChild, [child]),
            returnValue: _i3.Future<_i4.Result<_i15.ChildModel>>.value(
              _i6.dummyValue<_i4.Result<_i15.ChildModel>>(
                this,
                Invocation.method(#addChild, [child]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i15.ChildModel>>);

  @override
  _i3.Future<_i4.Result<_i15.ChildModel>> updateChild(_i15.ChildModel? child) =>
      (super.noSuchMethod(
            Invocation.method(#updateChild, [child]),
            returnValue: _i3.Future<_i4.Result<_i15.ChildModel>>.value(
              _i6.dummyValue<_i4.Result<_i15.ChildModel>>(
                this,
                Invocation.method(#updateChild, [child]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i15.ChildModel>>);

  @override
  _i3.Future<_i4.Result<void>> deleteChild(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChild, [id]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteChild, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}

/// A class which mocks [DashboardRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardRemoteDatasource extends _i1.Mock
    implements _i16.DashboardRemoteDatasource {
  MockDashboardRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i17.DashboardModel>> getDashboard() =>
      (super.noSuchMethod(
            Invocation.method(#getDashboard, []),
            returnValue: _i3.Future<_i4.Result<_i17.DashboardModel>>.value(
              _i6.dummyValue<_i4.Result<_i17.DashboardModel>>(
                this,
                Invocation.method(#getDashboard, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i17.DashboardModel>>);
}

/// A class which mocks [MedicationRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicationRemoteDatasource extends _i1.Mock
    implements _i18.MedicationRemoteDatasource {
  MockMedicationRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i19.MedicationModel>>> getMedications() =>
      (super.noSuchMethod(
            Invocation.method(#getMedications, []),
            returnValue:
                _i3.Future<_i4.Result<List<_i19.MedicationModel>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i19.MedicationModel>>>(
                    this,
                    Invocation.method(#getMedications, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i19.MedicationModel>>>);

  @override
  _i3.Future<_i4.Result<_i19.MedicationModel>> createMedication(
    _i19.MedicationModel? medication,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createMedication, [medication]),
            returnValue: _i3.Future<_i4.Result<_i19.MedicationModel>>.value(
              _i6.dummyValue<_i4.Result<_i19.MedicationModel>>(
                this,
                Invocation.method(#createMedication, [medication]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i19.MedicationModel>>);

  @override
  _i3.Future<_i4.Result<_i19.MedicationModel>> updateMedication(
    _i19.MedicationModel? medication,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMedication, [medication]),
            returnValue: _i3.Future<_i4.Result<_i19.MedicationModel>>.value(
              _i6.dummyValue<_i4.Result<_i19.MedicationModel>>(
                this,
                Invocation.method(#updateMedication, [medication]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i19.MedicationModel>>);

  @override
  _i3.Future<_i4.Result<void>> deleteMedication(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMedication, [id]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteMedication, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}

/// A class which mocks [ProfileRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRemoteDatasource extends _i1.Mock
    implements _i20.ProfileRemoteDatasource {
  MockProfileRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i21.UserModel>> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i3.Future<_i4.Result<_i21.UserModel>>.value(
              _i6.dummyValue<_i4.Result<_i21.UserModel>>(
                this,
                Invocation.method(#getProfile, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i21.UserModel>>);
}

/// A class which mocks [AuthRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDatasource extends _i1.Mock
    implements _i22.AuthRemoteDatasource {
  MockAuthRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i21.UserModel>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i3.Future<_i4.Result<_i21.UserModel>>.value(
              _i6.dummyValue<_i4.Result<_i21.UserModel>>(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i21.UserModel>>);
}

/// A class which mocks [AuthLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDatasource extends _i1.Mock
    implements _i23.AuthLocalDatasource {
  MockAuthLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveSession(
    _i21.UserModel? user, {
    bool? rememberMe = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveSession, [user], {#rememberMe: rememberMe}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearSession() =>
      (super.noSuchMethod(
            Invocation.method(#clearSession, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  bool isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i24.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Stream<bool> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i3.Stream<bool>.empty(),
          )
          as _i3.Stream<bool>);
}

/// A class which mocks [LocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorage extends _i1.Mock implements _i25.LocalStorage {
  MockLocalStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> put(String? boxName, String? key, dynamic value) =>
      (super.noSuchMethod(
            Invocation.method(#put, [boxName, key, value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  T? get<T>(String? boxName, String? key, {T? defaultValue}) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [boxName, key],
              {#defaultValue: defaultValue},
            ),
          )
          as T?);

  @override
  _i3.Future<void> clearBox(String? boxName) =>
      (super.noSuchMethod(
            Invocation.method(#clearBox, [boxName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [GraphQLService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGraphQLService extends _i1.Mock implements _i26.GraphQLService {
  MockGraphQLService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<Map<String, dynamic>>> query(
    String? document, {
    Map<String, dynamic>? variables,
    String? operationName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #query,
              [document],
              {#variables: variables, #operationName: operationName},
            ),
            returnValue: _i3.Future<_i4.Result<Map<String, dynamic>>>.value(
              _i6.dummyValue<_i4.Result<Map<String, dynamic>>>(
                this,
                Invocation.method(
                  #query,
                  [document],
                  {#variables: variables, #operationName: operationName},
                ),
              ),
            ),
          )
          as _i3.Future<_i4.Result<Map<String, dynamic>>>);

  @override
  _i3.Future<_i4.Result<Map<String, dynamic>>> mutate(
    String? document, {
    Map<String, dynamic>? variables,
    String? operationName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #mutate,
              [document],
              {#variables: variables, #operationName: operationName},
            ),
            returnValue: _i3.Future<_i4.Result<Map<String, dynamic>>>.value(
              _i6.dummyValue<_i4.Result<Map<String, dynamic>>>(
                this,
                Invocation.method(
                  #mutate,
                  [document],
                  {#variables: variables, #operationName: operationName},
                ),
              ),
            ),
          )
          as _i3.Future<_i4.Result<Map<String, dynamic>>>);
}

/// A class which mocks [GetChildrenUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetChildrenUseCase extends _i1.Mock
    implements _i27.GetChildrenUseCase {
  MockGetChildrenUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.ChildEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<_i4.Result<List<_i5.ChildEntity>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.ChildEntity>>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.ChildEntity>>>);
}

/// A class which mocks [GetChildDetailsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetChildDetailsUseCase extends _i1.Mock
    implements _i28.GetChildDetailsUseCase {
  MockGetChildDetailsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.ChildEntity>> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i3.Future<_i4.Result<_i5.ChildEntity>>.value(
              _i6.dummyValue<_i4.Result<_i5.ChildEntity>>(
                this,
                Invocation.method(#call, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.ChildEntity>>);
}

/// A class which mocks [GetMedicationsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMedicationsUseCase extends _i1.Mock
    implements _i29.GetMedicationsUseCase {
  MockGetMedicationsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i8.MedicationEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<_i4.Result<List<_i8.MedicationEntity>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i8.MedicationEntity>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i8.MedicationEntity>>>);
}

/// A class which mocks [CreateMedicationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateMedicationUseCase extends _i1.Mock
    implements _i30.CreateMedicationUseCase {
  MockCreateMedicationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i8.MedicationEntity>> call(
    _i8.MedicationEntity? medication,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [medication]),
            returnValue: _i3.Future<_i4.Result<_i8.MedicationEntity>>.value(
              _i6.dummyValue<_i4.Result<_i8.MedicationEntity>>(
                this,
                Invocation.method(#call, [medication]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i8.MedicationEntity>>);
}

/// A class which mocks [UpdateMedicationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateMedicationUseCase extends _i1.Mock
    implements _i31.UpdateMedicationUseCase {
  MockUpdateMedicationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i8.MedicationEntity>> call(
    _i8.MedicationEntity? medication,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [medication]),
            returnValue: _i3.Future<_i4.Result<_i8.MedicationEntity>>.value(
              _i6.dummyValue<_i4.Result<_i8.MedicationEntity>>(
                this,
                Invocation.method(#call, [medication]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i8.MedicationEntity>>);
}

/// A class which mocks [DeleteMedicationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteMedicationUseCase extends _i1.Mock
    implements _i32.DeleteMedicationUseCase {
  MockDeleteMedicationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<void>> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#call, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}

/// A class which mocks [GetDashboardUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDashboardUseCase extends _i1.Mock
    implements _i33.GetDashboardUseCase {
  MockGetDashboardUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i10.DashboardEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<_i4.Result<_i10.DashboardEntity>>.value(
              _i6.dummyValue<_i4.Result<_i10.DashboardEntity>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i10.DashboardEntity>>);
}

/// A class which mocks [GetProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProfileUseCase extends _i1.Mock implements _i34.GetProfileUseCase {
  MockGetProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i12.UserEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<_i4.Result<_i12.UserEntity>>.value(
              _i6.dummyValue<_i4.Result<_i12.UserEntity>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i12.UserEntity>>);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i35.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i12.UserEntity>> call(
    String? email,
    String? password, {
    bool? rememberMe = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #call,
              [email, password],
              {#rememberMe: rememberMe},
            ),
            returnValue: _i3.Future<_i4.Result<_i12.UserEntity>>.value(
              _i6.dummyValue<_i4.Result<_i12.UserEntity>>(
                this,
                Invocation.method(
                  #call,
                  [email, password],
                  {#rememberMe: rememberMe},
                ),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i12.UserEntity>>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i36.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<void>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}
